version: "3.9"

services:
  db:
    image: postgres:15
    container_name: atv_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clientesdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: atv_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: clientesdb
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  db_data:
